"""credential pool: drop unique on ip_or_cidr, add auto_discovered

Revision ID: 131f92cddb26
Revises: 97ec4108584e
Create Date: 2026-09-21 14:39:20.062854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131f92cddb26'
down_revision: Union[str, None] = '97ec4108584e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'snmp_credentials',
        sa.Column('auto_discovered', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.drop_index('ix_snmp_credentials_ip_or_cidr', table_name='snmp_credentials')
    op.create_index(op.f('ix_snmp_credentials_ip_or_cidr'), 'snmp_credentials', ['ip_or_cidr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snmp_credentials_ip_or_cidr'), table_name='snmp_credentials')
    op.create_index('ix_snmp_credentials_ip_or_cidr', 'snmp_credentials', ['ip_or_cidr'], unique=True)
    op.drop_column('snmp_credentials', 'auto_discovered')
    # ### end Alembic commands ###
