"""add relay_source_ips table

Revision ID: 3da774211b53
Revises: 131f92cddb26
Create Date: 2026-09-23 14:32:13.502677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da774211b53'
down_revision: Union[str, None] = '131f92cddb26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relay_source_ips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relay_source_ips_ip'), 'relay_source_ips', ['ip'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relay_source_ips_ip'), table_name='relay_source_ips')
    op.drop_table('relay_source_ips')
    # ### end Alembic commands ###
