"""add anomaly acknowledgments table

Revision ID: 79d12cac5594
Revises: 3da774211b53
Create Date: 2026-09-23 19:18:38.724585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d12cac5594'
down_revision: Union[str, None] = '3da774211b53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_acknowledgments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=False),
    sa.Column('anomaly_reason', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_ip', 'anomaly_reason', name='uq_anomaly_ack_device_reason')
    )
    op.create_index(op.f('ix_anomaly_acknowledgments_source_ip'), 'anomaly_acknowledgments', ['source_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_acknowledgments_source_ip'), table_name='anomaly_acknowledgments')
    op.drop_table('anomaly_acknowledgments')
    # ### end Alembic commands ###
