"""initial schema

Revision ID: bda3801cab38
Revises: 
Create Date: 2026-09-16 17:18:03.008831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda3801cab38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classification_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('predicted_category', sa.String(length=32), nullable=False),
    sa.Column('corrected_category', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_feedback_event_id'), 'classification_feedback', ['event_id'], unique=False)
    op.create_table('snmp_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip_or_cidr', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=8), nullable=False),
    sa.Column('community_encrypted', sa.String(length=512), nullable=True),
    sa.Column('v3_user', sa.String(length=128), nullable=True),
    sa.Column('v3_level', sa.String(length=32), nullable=True),
    sa.Column('v3_auth_proto', sa.String(length=16), nullable=True),
    sa.Column('v3_auth_pass_encrypted', sa.String(length=512), nullable=True),
    sa.Column('v3_priv_proto', sa.String(length=16), nullable=True),
    sa.Column('v3_priv_pass_encrypted', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snmp_credentials_ip_or_cidr'), 'snmp_credentials', ['ip_or_cidr'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snmp_credentials_ip_or_cidr'), table_name='snmp_credentials')
    op.drop_table('snmp_credentials')
    op.drop_index(op.f('ix_classification_feedback_event_id'), table_name='classification_feedback')
    op.drop_table('classification_feedback')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
